#!/usr/bin/env bun
import { cp, mkdir, rm, watch as fsWatch } from 'node:fs/promises';

const DIST = 'dist';
const ENTRY = 'src/index.ts';
const OUTFILE = `${DIST}/Code.js`;

const BANNER = `// Generated by Bun.build — do not edit by hand.
// Source: https://github.com/rijoanul-shanto/meet-or-miss (see README.md)`;

const FOOTER = `
function checkUpcomingMeetings() { return globalThis.__meetingsReminder_check(); }
function healthCheck() { return globalThis.__meetingsReminder_health(); }
`;

async function build(): Promise<void> {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });
  await cp('src/appsscript.json', `${DIST}/appsscript.json`);

  const result = await Bun.build({
    entrypoints: [ENTRY],
    outdir: DIST,
    target: 'browser',
    format: 'iife',
    naming: 'Code.js',
    minify: false,
    sourcemap: 'none',
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }

  const bundled = await Bun.file(OUTFILE).text();
  await Bun.write(OUTFILE, `${BANNER}\n${bundled}\n${FOOTER}`);
  console.log(`Built ${OUTFILE}`);
}

async function watchMode(): Promise<void> {
  await build();
  console.log('Watching src/ for changes…');
  const watcher = fsWatch('src', { recursive: true });
  for await (const _event of watcher) {
    console.log('Change detected, rebuilding…');
    try {
      await build();
    } catch (err) {
      console.error('Build failed:', err);
    }
  }
}

if (process.argv.includes('--watch')) {
  await watchMode();
} else {
  await build();
}
